version: '3.4'

services:
  dotnet.tdd.deskbooking.db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DotNetTDD2022

  dotnet.tdd.deskbooking.api:
    image: ${DOCKER_REGISTRY-}dotnettdddeskbookingapi
    build:
      context: .
      dockerfile: Src/DotNet.TDD.DeskBooking.API/Dockerfile
    depends_on:
      - dotnet.tdd.deskbooking.db